# Generated by Django 3.1.7 on 2022-01-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=64),
        ),
    ]
