# Generated by Django 3.1.7 on 2022-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='certificate',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
