# Generated by Django 4.0 on 2021-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0002_alter_match_number_of_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='number_of_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
