# Generated by Django 4.0 on 2021-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0003_alter_match_number_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchased',
            field=models.BooleanField(default=True),
        ),
    ]
