# Generated by Django 4.0 on 2021-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0006_remove_ticket_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
