# Generated by Django 4.0 on 2021-12-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0007_ticket_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup22.match'),
        ),
    ]
