# Generated by Django 4.0 on 2021-12-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0009_alter_ticket_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
    ]
