# Generated by Django 4.0 on 2022-01-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0011_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
