# Generated by Django 3.1.7 on 2022-01-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0013_auto_20220101_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
