# Generated by Django 3.1.7 on 2022-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup22', '0014_auto_20220101_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchased',
        ),
        migrations.AddField(
            model_name='vote',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
