# Generated by Django 4.0 on 2021-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default='', max_length=16),
        ),
    ]
